# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by libcurl! Edit at your own risk.

www.meteo.lv	FALSE	/	FALSE	0	JSESSIONID	67A94363D6FD5FADE252234A55D24697
www.meteo.lv	FALSE	/josso	TRUE	0	JSESSIONID	06DF5BEDFF09DF1062A164DF22801AF2
